name: automated tests
on:
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: macos-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Mochawesome dependencies for reporting
      run: npm i --save-dev cypress-mochawesome-reporter

    - name: Run automated tests
      run: npm run test
